application:
  port: 8080
  prefix: 'api'
  version: 1.0.0

# MySQL数据库配置
mysql:
  db: ''
  host: ''
  port: 3306
  username: ''
  password: ''
  synchronize: false
  logging: false

# Redis配置
redis:
  host: ''
  port: 6379

# 阿里OSS配置
oss:
  endpoint: ''
  accessKeyId: ''
  accessKeySecret: ''
  bucket: ''
