application:
  port: 8081
  prefix: 'api'
  version: 1.0.0

# MySQL数据库配置
mysql:
  db: '自定义库名'
  host: 'localhost'
  port: 3306
  username: 'root'
  password: 'root'
  synchronize: true
  logging: true

# Redis配置
redis:
  host: ''
  port: 6379

# 阿里OSS配置
oss:
  endpoint: ''
  accessKeyId: ''
  accessKeySecret: ''
  bucket: ''
